[project]
name = "msba405-sample-pipeline"
version = "0.1.0"
dependencies = [
    "six",
    "luigi",
    "duckdb"
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
